### ISSUE TITLE
Establish Regular Member Meeting Times

### ISSUE THREAD

**Issue by JordanMajd** [CodeForFoco/org#1]
We need to establish a regular meeting time for the organization.
- Preferably a Thursday or a Friday.
- Biweekly or monthly
- Initially could  be over lunch, but as the org grows should be after work hours.

**Comment by p5150j** [comment]
Let's shoot for Friday's as I'm in Fort Collins Thursday and Friday.... Thursdays usually catch up work for me though. Friday's just work meetings so let's shoot for that

**Comment by JordanMajd** [comment]
For now we could do a Friday lunch meeting every or every other week. As we expand we could switch it to a Friday afterwork meeting. Thoughts?

**Comment by JordanMajd** [comment]
@p5150j 

Organizational meeting is set for Friday at 12:00

**Comment by p5150j** [comment]
👍
