### ISSUE TITLE
Logo Vote

### ISSUE THREAD

**Issue by JordanMajd** [CodeForFoco/org#12]
@taramason 's designs are up and voting is now open!

![20160602_225424](https://cloud.githubusercontent.com/assets/1037492/15975479/e99f2ab2-2f0a-11e6-835f-0666305544fc.jpg)

Please respond with A, B, C or D, where D is other.

Voting closes at the end of day on Wednesday the 15th.

**Comment by Jayme-T** [comment]
C

**Comment by ghost** [comment]
C

**Comment by p5150j** [comment]
C

**Comment by JordanMajd** [comment]
C

**Comment by gabethexton** [comment]
B

**Comment by DanielDwyer** [comment]
C

**Comment by S204STi** [comment]
C

**Comment by spogburn** [comment]
B

**Comment by JordanMajd** [comment]
C is the winner! @taramason 

## Results:
- C - 6 votes
- B - 2 votes
- A - 0 votes
- D - 0 votes
