### ISSUE TITLE
How to Pitch an idea

### ISSUE THREAD

**Issue by Jayme-T** [CodeForFoco/org#13]
## Description

It would be helpful to create a standard of how pitch nights will look. If we are truly hoping to grow as an organization it would be good to go in with the idea that it is possible a lot of people will want to pitch ideas and by creating a format that people adhere to we can better support and prepare to help a variety of people/organization within our community. I am opening this issue as a place/reminder to start coming up with ideas of what you feel the pitch ideas should include (what does a successful pitch look like to you)
### Possible Checklist

These are some ideas of things we may ask the user to include. Again these are just ideas to get everyone thinking about what people need/want to know about a pitch 
- organization name/purpose
- who benefits from the idea being pitched
- how do they benefit
### Questions
- Do we want to have a open pitch night where anyone can pitch an idea 
- Do we want people to sign up or apply to pitch so we know what to prepare for
- How do we decide the outcome of pitch night? Community vote? Multiple outcomes?
- Do we decide the outcome at pitch night or discuss it and announce later?
-  Should each pitch be under a certain length of time
- Should organizations be allowed to pitch the same idea at multiple pitch nights or should we ask that the ideas be changed?
  ### General

Please come up with any other thoughts or ideas about what a pitch night might look like.

**Comment by JordanMajd** [comment]
Thanks for opening up the discussion on this. Let's make this a topic of Friday's meeting.

**Comment by JordanMajd** [comment]
I'm going to close this issue for the time being since we aren't focusing on a pitch off.

This will be re opened when we decide to have our first pitch night because it has some great points to consider.
