### ISSUE TITLE
Need to cread an Onboarding.md 

### ISSUE THREAD

**Issue by itorain** [CodeForFoco/org#15]
Create an Onboarding readme with instructions. Instructions are:
* Pair with someone. Ideally there will be someone responsible for onboarding at meetings to pair with.
* Get into Slack and how to get started with slack
* How to setup github, and cloning website code
* How to contribute/link to how to contribute.md
## In the future add a github getting started documentation ( or link to freecodecamp github module).

**Comment by itorain** [comment]
freecodecamp link(https://www.freecodecamp.com/challenges/save-your-code-revisions-forever-with-git)

**Comment by englehorn** [comment]
I created a unboarding.md. Request to close this file. We are going to merge this with the contributing documenting.
