### ISSUE TITLE
Acquire and setup Domain

### ISSUE THREAD

**Issue by JordanMajd** [CodeForFoco/org#2]
Need to acquire domain [codeforfoco.org](codeforfoco.org) and set it up to work with github pages.

**Comment by JordanMajd** [comment]
Domain purchased, opening up issue on website to configure.

**Comment by p5150j** [comment]
Let me know if you need to spring for cash

**Comment by JordanMajd** [comment]
Thanks, I'm not worried about it. Domain was pretty cheap.  At some point it might be fun to get `codeforfo.co` haha.
