### ISSUE TITLE
We should be listed on all CFA Listings

### ISSUE THREAD

**Issue by JordanMajd** [CodeForFoco/org#21]
We should contact CFA and ensure we are listed everywhere on their site:

- We are not listed on the [CFA Brigade Map](http://brigade.codeforamerica.org/brigade/)
- We are not listed in the [CFA Brigades List](https://www.codeforamerica.org/join-us/volunteer-with-us/list-of-all-brigades)
- ~We are not listed on map in [Volunteer With Us](http://codeforamerica.org/join-us/volunteer-with-us)~
- ~Not listed on donations form.~

**Comment by JordanMajd** [comment]
Emailed Monique

**Comment by JordanMajd** [comment]
CFA got back to us and said she would look into adding us to the listings. However, it seems that went nowhere.

**Comment by davidbhayes** [comment]
The listed map and listing above seem to have been consolidated onto https://brigade.codeforamerica.org/. But we're not there. I'm working on this though

**Comment by davidbhayes** [comment]
I think I got to the bottom of this. We're not on this (https://docs.google.com/spreadsheets/d/1zglhAKDUNnvKindAhb6K_DJaLQ_myRYGKvE2DTYolAQ/edit#gid=0) and that seems to be the core of the issue. Have started that process, I think

**Comment by davidbhayes** [comment]
Resolved! Thanks to @tdooner and the CFA staff 🙌 We're all over: https://brigade.codeforamerica.org/

**Comment by tdooner** [comment]
We're glad to have you back on the map! 🎉
