### ISSUE TITLE
Farm Network

### ISSUE THREAD

**Issue by abettermap** [CodeForFoco/org#23]
- Compost database
- Local farm map
- @englehorn @abettermap @menlatin more input...

**Comment by englehorn** [comment]
I researched the Growing Project Community Compost site. It looks like the project has a map and small network of composting sites. Here are the links:
http://www.fcgov.com/recycling/composting.php
http://www.thegrowingproject.org/community-composting-the-compost-commons.html

**Comment by englehorn** [comment]
This is an app that was developed by the Siskiyou Farm Cooperative in
Williams Oregon. It is an open source Heroku app and helps CSA members
learn about memberships, recipes, cooking and food info.

http://www.siskiyoucoop.com/csa/app/
@abettermap @menlatin

**Comment by abettermap** [comment]
Open-source as in they used open-source tech or as in their code is available? I couldn't find it.

Growing Project only has 3 sites so the map is probably sufficient, but if they could benefit from anything additional then I am open to ideas.

**Comment by davidbhayes** [comment]
Moving to Wiki
