### ISSUE TITLE
Create Meetup Group

### ISSUE THREAD

**Issue by JordanMajd** [CodeForFoco/org#3]
Need to create a [Meetup](meetup) group where we can post our events.

**Comment by p5150j** [comment]
Spoke with Shareese and she said we can use the Galvanize Meetup page!! She also said there's two or three others that she has created that we have full access to

**Comment by JordanMajd** [comment]
Awesome, it would be pretty cool to be able to use that page because the people who are already a part of that community.

I can only see one downside, it might be useful to have our own instead in the likely hood that we host events at other locations as well.  For example, if we had a Teach Kids to Code event at a middle school.

I might be over thinking it, or that could just be a problem we deal with when we get there.

Next time I see her I'll ask her more about that.

**Comment by JordanMajd** [comment]
@p5150j I followed with Charisse and arrived at a decision,
- We will initially start using the Galvanize meetup group.
- Once we are more established, we will create our own.
