### ISSUE TITLE
Document and task out marketing strategy

### ISSUE THREAD

**Issue by davidbhayes** [CodeForFoco/org#38]
Who are we trying to get the attention of? What do we want that attention for?

**Comment by davidbhayes** [comment]
Social media for...?

Possibilities:

- Recruit new member
- Keep existing members informed
- Keep the community (non-members) about what we're doing

**Comment by JordanMajd** [comment]
Per our discussion tonight I will task out each item in the google doc, which should address this issue.

**Comment by JordanMajd** [comment]
I believe I've tasked out all of the items that Megan listed out. It would probably be good to create an `md` or wiki page with the strategy on it too. Just so it doesn't get lost with time but we have a reference we can always come back to.
