### ISSUE TITLE
How do we put websites online? How do we pay for them (and other things)?

### ISSUE THREAD

**Issue by davidbhayes** [CodeForFoco/org#39]
The heart is that it'd be really cool that we could buy hosting for the Solar Scorecard, CERP, etc somewhere. But we don't have a method right now.

**Comment by davidbhayes** [comment]
@JordanMajd Can we spend money through either LaunchNo.Co or CFA if we were to raise it? I'd be happy to put some money in, but it'd be great if we had an easy method of spending what funds we have.

**Comment by JordanMajd** [comment]
I've been playing phone tag w/ Jana. I'll bring this up with her.
