### ISSUE TITLE
Create Twitter and other social media accounts

### ISSUE THREAD

**Issue by JordanMajd** [CodeForFoco/org#4]
We need to create twitter and social media accounts to start spreading awareness of the organization and making connections within our community.

**Comment by gabethexton** [comment]
Is there a base set of credentials we want to use for these?
I wouldn't mind going through and registering a bunch just to have them on lockdown.

namechk.com makes it easy to know what's available and codeforfoco looks really good (see attached)
[namechk_services_codeforfoco.xlsx](https://github.com/CodeForFoco/org/files/267386/namechk_services_codeforfoco.xlsx)

**Comment by JordanMajd** [comment]
I haven't figured out what to do as far as credentials goes.

I was thinking we could have one master password hidden away that only a few people knew, and then use something like tweet deck to grant access to anyone who wants to post on the orgs behalf.

**Comment by JordanMajd** [comment]
@jeremyroelfs @gabethexton 

Can you guys coordinate on getting us a FB page and a Twitter handle.

Currently I have, admin@codeforfoco.org pointing to Gabes email but I can update to forward it to whoever.

**Comment by JordanMajd** [comment]
We have the following social media accounts:

[Twitter is @codeforfoco](https://twitter.com/codeforfoco)
[Facebook is Code for Foco](https://www.facebook.com/CodeforFoCo)
[Meetups is Code for Fort Collins](http://www.meetup.com/Code-for-Fort-Collins/)

If you would like access to them PM on slack. Thanks
