### ISSUE TITLE
Plan out 3 community events

### ISSUE THREAD

**Issue by davidbhayes** [CodeForFoco/org#40]
Hackathon? Pitch competition? Non-profit fair?

**Comment by davidbhayes** [comment]
Randomly was talking to a friend (Kelly) who recommended that we could find cheap or free event space at...

- The City of Fort Collins has some community rooms
- The Poudre River Library offers free room booking (subject to availability)
- The Group (the real estate company, has office off Harmony + Corbett)

**Comment by davidbhayes** [comment]
Outline from Megan + David brainstorm

- One hackathon
- One workshop
- Two parties

**Comment by JordanMajd** [comment]
On board for setting a goal to making events happen. A hackathon, a workshop and a party all sound good. This will also help us move in the direction we need to for sponsorship.

Let's set rough dates for each of these events and put together a roadmap of everything we will need to do to make the event a success (marketing, sponsorship etc...)

**Comment by JordanMajd** [comment]
Notes from meeting w/ Dan:

- To keep people involved we host a quarterly event.
- Specifically look for partners to throw the event with.
- Starting with women who code group.

**Comment by JordanMajd** [comment]
Related notes from meeting with Dan:

- One of the quarterly meetups being specifically about pulling a bunch of volunteer organizations in a room. People share they successes of using tech in nonprofit space.

- Throwing events and hosting speakers from other organizations. Lets all meet and listen to this person and then mingle afterwards. Something like the startup week.
