### ISSUE TITLE
Should we use the Wiki for process documentation? .md files in this repo? Other?

### ISSUE THREAD

**Issue by davidbhayes** [CodeForFoco/org#42]
Wiki Pros:

- Integrated into GitHub
- Possibly simpler for newbies

.md Pros:

- Commit credit ;p
- More "hacker"

**Comment by JordanMajd** [comment]
I'm partial to using `.md`, I use it for all of my personal note taking, all of my dev documentation etc....

At the moment nobody seems to read our files, but that might have more to do with the fact that they don't have useful information.

Anybody else have preferences?
