### ISSUE TITLE
Strategize meetup finances: how do we pay for things?

### ISSUE THREAD

**Issue by davidbhayes** [CodeForFoco/org#43]
Can we get a credit card? Debit? Paypal?

**Comment by JordanMajd** [comment]
We can get a card from CFA for our account with them if donations go through them. I'm trying to talk with Janna to see what launch NoCo offers but I haven't been available / she hasn't been available when we've tried.

**Comment by JordanMajd** [comment]
Things to pay for:

- Domains
- Hosting
- Spontaneous monthly surprises like cupcakes
- Beer
- Pizza
- Event space
- Hackathon Prizes

**Comment by davidbhayes** [comment]
The answer to this is pretty clear, as a Code for America brigade. They're a fiduciary, which means, in short:  

- If/when we raise money from anyone, we get it donated to Code for America, with a designation that it's for us.
- If/we we spend money, it needs to go a brigade member's card. We then submit the cost as an expense to CFA, and that brigade member is reimbursed.

I'll expand on this and post it in the root of the org repo.
