### ISSUE TITLE
Change location of social night to be more inclusive.

### ISSUE THREAD

**Issue by JordanMajd** [CodeForFoco/org#48]
Move social night to somewhere that members who don't drink or are under 21 feel welcome.

**Comment by peglegmeg** [comment]
Ideas
- Tea shop or coffee shop?
- Somewhere closer to campus
- Moe's, Jim's Wings, or Illegal Pete's (easy to eat / drink / both / neither)
- Wild Boar
- Bowling!
- Pub quiz?

**Comment by peglegmeg** [comment]
"Trader Joe's" -- David

**Comment by davidbhayes** [comment]
## Proposal of upcoming locations

December: Wild Boar (tea/cofee/wine/food, near Prospect & College)
January: Jim's Wings (wings, beer, Campus West)
Feb: Coopersmiths (Old Town Square)

**Comment by peglegmeg** [comment]
Hear hear!

**Comment by davidbhayes** [comment]
Closed as we're reducing the number of social nights and probably won't travel with them away from Cohere soon
