### ISSUE TITLE
Set up email marketing campaign

### ISSUE THREAD

**Issue by JordanMajd** [CodeForFoco/org#55]
- [ ] Sign up for mailchimp.
- [ ] Collect all email addresses for current members/attendees.
- [ ] Start taking a formal “attendance” at meetings/collecting contact info.
- [ ] Send welcome email.
  - Include link to code of conduct.
  - Build survey about goals / interests
  - Add links to GitHub, Slack, etc.
- [ ] Write monthly emails to entire listserv
- [ ] Manage list serv
- [ ] Emails should communicate what people are currently working on and what the needs are for each project.

**Comment by JordanMajd** [comment]
See also #44

**Comment by davidbhayes** [comment]
Closing as using Meetup emails is an easier and good-enough solution given our current amount of leadership capacity
