### ISSUE TITLE
Meet with local nonprofit members.

### ISSUE THREAD

**Issue by JordanMajd** [CodeForFoco/org#58]
Meet with local nonprofits to learn and talk with them on a monthly basis.

**Comment by JordanMajd** [comment]
Related discussion with Dan, after visiting CFA Congress:


Becoming a Servant volunteer group:

- Most successful and impactful projects are driven by other groups.
- Code for * brigades are driving a tech solution for it.

How would you execute:

- One of the quarterly meetups being specifically about pulling a bunch of volunteer organizations in a room. People share they successes of using tech in nonprofit space.

- We have a website and a meetup, but hard to tell how far that penetrates. Sending a letter to them might do what passive advertising does not.

- Go out and have coffee with them, meet them in their offices.

Not an open call for projects but a hey have you heard about us.

The best project ideas will come from people who know we are an organization and they will come up with ideas and bring it to us.

Throwing events and hosting speakers from other organizations. Lets all meet and listen to this person and then mingle afterwards. Something like the startup week.

Projects that come from existing groups, solving existing problems will have a wider variety of tasks including user testing and design. Just working with a partner is a job for a volunteer.

**Comment by davidbhayes** [comment]
Can we plan to do this (a big single event to have local nonprofits talk to us and each other about technology) in February or March? I think this basic idea of trying to find local stakeholders and pull them all into the same room would be good for us. Should this be a first-of-the-month meeting? Or should we do it some other time?

**Comment by davidbhayes** [comment]
Actually, let's plan to do this on Thursday, March 1 during 2018 Startup Week. That could work really well. Let's plan to hold a "technology and nonprofits" panel/event and party.

**Comment by peglegmeg** [comment]
To clarify, we would like to host an event during start up week that invites area nonprofits and do a soft-pitch to ask for projects? 

I think the core idea is great. We will just need to outline some goals and how we want to execute them and measure their success.

**Comment by davidbhayes** [comment]
It's a combo. A celebration of us, and them, and a summit sort of event so they can talk to each other and to us. Ideally we can give valuable insight/information for people who aren't going to have a project for us right now but so they want to come anyway

**Comment by peglegmeg** [comment]
Got it. Budget? @JordanMajd

**Comment by JordanMajd** [comment]
We'll have to list out what our needs are and what the cost will be. Then seek out in kind donations (new belgium 60 or 90 days in advance for free beer, Techsystems for more free beer and food)  as well as sponsors for the event.

**Comment by peglegmeg** [comment]
Helpful. I'll start putting together a project in GitHub and go from there.
Thanks!

Megan Lee
www.meetmeganlee.com
LinkedIn <http://www.linkedin.com/in/leemeganelizabeth/> | Twitter
<http://twitter.com/peglegmeg> | Google+
<https://plus.google.com/+MeganLeeMeihua/posts>

**Comment by davidbhayes** [comment]
Setting up a coffee meeting now with Grant Stump from United Way

**Comment by davidbhayes** [comment]
Closing as the discussion is largely off topic (an event we're not doing now). But this is a good idea and one I'm personally managing for right now
