### ISSUE TITLE
Make document of community contacts

### ISSUE THREAD

**Issue by JordanMajd** [CodeForFoco/org#59]
Keep a list of relevant groups and their contacts. This can be used to plan events together.

- Women Who Code, Girl Develop It.

**Comment by JordanMajd** [comment]
Related: #61

**Comment by JordanMajd** [comment]
Related: #65

**Comment by davidbhayes** [comment]
@peglegmeg is building a Google Doc Sheet for this. I don't like Google Docs 🤓

**Comment by peglegmeg** [comment]
David is a baby! 👼🍼🐥👶🐣🚼

Megan Lee
www.meetmeganlee.com
LinkedIn <http://www.linkedin.com/in/leemeganelizabeth/> | Twitter
<http://twitter.com/peglegmeg> | Google+
<https://plus.google.com/+MeganLeeMeihua/posts>
