### ISSUE TITLE
Register brigade with Code for America

### ISSUE THREAD

**Issue by JordanMajd** [CodeForFoco/org#6]
We need to officially register our chapter with Code for America. In order to do so we must complete the following:
- ~~Core Team~~
- Strategic Plan #9 
- ~~Code of Conduct~~ #7
- ~~Community Partners~~ #11 
- ~~Government Partners~~  #8 

Just because a task has been completed doesn't mean that it can't be improved!

**Comment by p5150j** [comment]
I'll get with Joesph and see if he can hook us up real quick

**Comment by JordanMajd** [comment]
Cool I've been looking over the [Organizers Checklist](https://www.codeforamerica.org/brigade/organize/) and the [Brigade Organizers Playbook](https://docs.google.com/document/d/19bN5RWK5nQTpz0mHUViHrzHiommBUAMSztwNRzUcxYo/edit#heading=h.i0zqlxd516hk) which lists out what are the requirements to become a brigade.
- Core Team (currently just you and me)
- Strategic Plan (I'll create an issue for this)
- Code of Conduct (I'll create an issue for this)
- Community Partner (Galvanize - we can always have more just might want to finish site first)
- Government Partner (I have some Foco gov and State gov connections, I'll create an issue for this)

**Comment by JordanMajd** [comment]
We are official!
