### ISSUE TITLE
Engage with other local brigades

### ISSUE THREAD

**Issue by JordanMajd** [CodeForFoco/org#65]
A lot of the Brigades that come from the same state have shared projects and communication (like a shared slack). 

Reach out to Code for Boulder and Denver. Remember to document them as community contacts (see #59 )

**Comment by davidbhayes** [comment]
Who should own this? I'd be happy to do it, though if you know anyone @JordanMajd I'm also happy for you to lead

**Comment by davidbhayes** [comment]
I'm on this. I reached out to both CFBoulder and CFDenber this morning.

**Comment by davidbhayes** [comment]
I'm closing this as complete. I've got pretty good connection with the Code for Boulder people, and have talked to Denver once. I'm starting a regular every-other month Code for Colorado brigade meeting which will happen for the first time on Tuesday evening September 4, 2018. Writing down now to email everyone on that soon though 🤓
