### ISSUE TITLE
Remake connections with Code for America laisons

### ISSUE THREAD

**Issue by JordanMajd** [CodeForFoco/org#66]
Reach out to Erie and Christopher at CFA to talk with them more to understand how they could support us and let them know what our needs are.

**Comment by peglegmeg** [comment]
When we do this, can we also ask them for ideas for events that they've held in the past—or other code groups have held in the past—that have shown great success? It would be helpful to get insight before we plan our March event. Thanks JorJor!!

**Comment by davidbhayes** [comment]
This one if for me to speak to someone there, and be in their Slack. @DanLaRoche is helping.

I'm also hoping that CFBoulder and or CFDenver could help up with this.

**Comment by davidbhayes** [comment]
I've gotten into the Slack. A lot of answers about the CFA support are also likely at: https://brigade.codeforamerica.org/resources, which I haven't yet read in full.

**Comment by davidbhayes** [comment]
@DanLaRoche and I are scheduling a meeting with their on-boarding coordinator now. I think I'll close this as in-progress and not needing to still exist here.
