### ISSUE TITLE
Email Women Who Code about FCSW event

### ISSUE THREAD

**Issue by JordanMajd** [CodeForFoco/org#72]
Arrange phone call to discuss / collaborate the event.

Focus: 
- How coders can be a positive influence in their community (or something).
- How tech orgs are (can / want) helping local nonprofits?

Would they be interested in cohosting?
Who else would be interested in participating?
Panel or speaker?

**Comment by davidbhayes** [comment]
This is running dropped. I do need to follow up with Lindsay soon though
