### ISSUE TITLE
Establish Government Partnerships

### ISSUE THREAD

**Issue by JordanMajd** [CodeForFoco/org#8]
We need to establish a solid relationship with our local government. I will be updating this post with the current status.
### Current Partnerships:
- City of Fort Collins: Ginny Sawyer, Project Manager for Open Data Initiative
### Currently in progress:
- Secretary of State: Andrew Cole, he is in charge of the state's Open Data Initiative and their hackathon Go Code Colorado.
- City of Fort Collins: Susie Gordan, Natural Resources - @Jayme-T 
- Colorado State: Kori Donaldson, Legislative Council - @taramason  
### Near term todo:
- City of Fort Collins: Sam, he is in charge of running a hackathon to get an application built for local farmers.
### Longer term todo:
- Larimer County
### Resources
- [Code for America tips](https://docs.google.com/document/d/19bN5RWK5nQTpz0mHUViHrzHiommBUAMSztwNRzUcxYo/edit#heading=h.5loldkzhmzpp)

**Comment by JordanMajd** [comment]
Sent an email to Ginny, a project manager in charge of Fort Collins' open data initiative.

**Comment by JordanMajd** [comment]
TODO: Open communications with Sam at FC Gov. about hackathon. Charisse and Ginny both know.

**Comment by JordanMajd** [comment]
Ginny will be joining our org meeting on Friday, May 20th!

**Comment by JordanMajd** [comment]
@taramason I'd love to talk sometime more about your connections at the Capital.

**Comment by taramason** [comment]
@JordanMajd sounds good, anytime. This is her slower time since the House is not in session. I think she was hoping to come up to foco to spend time with her nephew so maybe we could plan to have her up on a Friday when we meet? Or we can set something else up, let me know what u you're thinking!

**Comment by Jayme-T** [comment]
Hey I also sent an e-mail to Susie Gordan she is in charge of the natural resource department for the City and I have done a few projects with her in the past. I just let her know we exist and a bit about us so she can help connect us to people or people to us. As we get more information she said she would like to sit down with us and hear more.

**Comment by taramason** [comment]
@JordanMajd - my contact at the State capital is going to be in town May 20th, I think she is on board with coming in to our meeting that day, but I am just realizing we scheduled someone from the city that day too? Will that work to have both of them?  I don't know if I will be able to get her up here again very soon...  Maybe a few months from now.

**Comment by JordanMajd** [comment]
@taramason

It will work to have both of them. That should actually work out quite well!

**Comment by taramason** [comment]
@JordanMajd -Her name is Kori Donaldson, Legislative Council, Colorado State

**Comment by JordanMajd** [comment]
Today we are meeting with Ginny Sawyer, will update afterwards.

**Comment by JordanMajd** [comment]
Partnership established with city of fort collins!

**Comment by JordanMajd** [comment]
Closed and am creating a document to track this
