### ISSUE TITLE
Request codeforfoco.org email for Theresa

### ISSUE THREAD

**Issue by stevenabadie** [CodeForFoco/org#90]

**Comment by stevenabadie** [comment]
@tfischbach you should be getting an email to your personal email to finish setting up the codeforfoco.org email. Going to close this out but feel free to reopen if you don't get the email.

**Comment by tfischbach** [comment]
Have not seen an email about this - do you know where it would be coming from?

**Comment by stevenabadie** [comment]
I think it should have gone to your personal gmail but maybe it didn't auto-send. Ceci gave us admin access to the org now so I've just sent the password reset request to your personal email.

**Comment by tfischbach** [comment]
and all good!
